{"name": "Проверка вывода ошибки при создании пользователя с данными которые уже зарегистрированы", "status": "passed", "steps": [{"name": "Отправляем POST запрос", "status": "passed", "parameters": [{"name": "endpoint", "value": "'/api/auth/register'"}, {"name": "data", "value": "{'email': 'fTr1zgyG@mail.ru', 'password': 'DZLGkudrZozz', 'name': 'vGOSdqE58rzK'}"}], "start": 1735277491910, "stop": 1735277492265}, {"name": "Проверяем статус код", "status": "passed", "parameters": [{"name": "code", "value": "403"}], "start": 1735277492265, "stop": 1735277492265}], "attachments": [{"name": "stdout", "source": "6da32418-7625-4778-baa8-82328eabe206-attachment.txt", "type": "text/plain"}], "start": 1735277491910, "stop": 1735277492265, "uuid": "437348f1-825b-49cb-97a8-af2442dd9794", "historyId": "a905236bf467a4fe26fed96e2e0d1cdc", "testCaseId": "a905236bf467a4fe26fed96e2e0d1cdc", "fullName": "tests.test_create_user.TestCreateUser#test_error_on_duplicate_user_creation", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-SQI1DNR"}, {"name": "thread", "value": "235160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}