{"name": "Проверка получения списка заказов не авторизованного пользователя", "status": "passed", "steps": [{"name": "Проверяем статус код", "status": "passed", "parameters": [{"name": "code", "value": "401"}], "start": 1735277493223, "stop": 1735277493223}], "attachments": [{"name": "stdout", "source": "72ff615a-03c1-43e7-af4e-070d038fe175-attachment.txt", "type": "text/plain"}], "start": 1735277492882, "stop": 1735277493223, "uuid": "6ad2c9bf-813e-4ea0-9c78-72ac5493cb6d", "historyId": "6c6683da0f2f7ab6bd5781099125dc3e", "testCaseId": "6c6683da0f2f7ab6bd5781099125dc3e", "fullName": "tests.test_get_orders.TestGetOrders#test_error_get_orders_list_with_unauthorized_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders"}, {"name": "subSuite", "value": "TestGetOrders"}, {"name": "host", "value": "DESKTOP-SQI1DNR"}, {"name": "thread", "value": "235160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders"}]}